---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-operator-controller-manager
  namespace: openebs-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-operator-controller-manager
  namespace: openebs-operator-system
  labels:
    app.kubernetes.io/name: openebs-operator
    app.kubernetes.io/component: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openebs-operator
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openebs-operator
        app.kubernetes.io/component: manager
    spec:
      serviceAccountName: openebs-operator-controller-manager
      containers:
        - name: manager
          image: ghcr.io/lukaspj/openebs-operator:latest
          imagePullPolicy: IfNotPresent
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8080
            - --leader-elect=false
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
