//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Package v1alpha1 contains API Schema definitions for the storage v1alpha1 API group.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another OpenEBS.
func (in *OpenEBS) DeepCopyInto(out *OpenEBS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = *in.Spec.DeepCopy()
	out.Status = *in.Status.DeepCopy()
}

// DeepCopy returns a deep copy of OpenEBS.
func (in *OpenEBS) DeepCopy() *OpenEBS {
	if in == nil {
		return nil
	}
	out := new(OpenEBS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *OpenEBS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OpenEBSList.
func (in *OpenEBSList) DeepCopyInto(out *OpenEBSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenEBS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of OpenEBSList.
func (in *OpenEBSList) DeepCopy() *OpenEBSList {
	if in == nil {
		return nil
	}
	out := new(OpenEBSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *OpenEBSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OpenEBSSpec.
func (in *OpenEBSSpec) DeepCopyInto(out *OpenEBSSpec) {
	*out = *in
	if in.Hostpath != nil {
		in, out := &in.Hostpath, &out.Hostpath
		*out = new(HostpathConfig)
		**out = **in
	}
	if in.LVM != nil {
		in, out := &in.LVM, &out.LVM
		*out = new(LVMConfig)
		**out = **in
	}
	if in.ZFS != nil {
		in, out := &in.ZFS, &out.ZFS
		*out = new(ZFSConfig)
		**out = **in
	}
	if in.Rawfile != nil {
		in, out := &in.Rawfile, &out.Rawfile
		*out = new(RawfileConfig)
		**out = **in
	}
	if in.Mayastor != nil {
		in, out := &in.Mayastor, &out.Mayastor
		*out = new(MayastorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(ImageConfig)
		**out = **in
	}
}

// DeepCopy returns a deep copy of OpenEBSSpec.
func (in *OpenEBSSpec) DeepCopy() *OpenEBSSpec {
	if in == nil {
		return nil
	}
	out := new(OpenEBSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another OpenEBSStatus.
func (in *OpenEBSStatus) DeepCopyInto(out *OpenEBSStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Engines != nil {
		in, out := &in.Engines, &out.Engines
		*out = make([]EngineStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of OpenEBSStatus.
func (in *OpenEBSStatus) DeepCopy() *OpenEBSStatus {
	if in == nil {
		return nil
	}
	out := new(OpenEBSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another ImageConfig.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
}

// DeepCopy returns a deep copy of ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another MayastorConfig.
func (in *MayastorConfig) DeepCopyInto(out *MayastorConfig) {
	*out = *in
	if in.IOEngineResources != nil {
		in, out := &in.IOEngineResources, &out.IOEngineResources
		*out = new(ResourceSpec)
		**out = **in
	}
	if in.CoreAgentResources != nil {
		in, out := &in.CoreAgentResources, &out.CoreAgentResources
		*out = new(ResourceSpec)
		**out = **in
	}
}

// DeepCopy returns a deep copy of MayastorConfig.
func (in *MayastorConfig) DeepCopy() *MayastorConfig {
	if in == nil {
		return nil
	}
	out := new(MayastorConfig)
	in.DeepCopyInto(out)
	return out
}

func init() {
	SchemeBuilder.Register(&OpenEBS{}, &OpenEBSList{})
}
